### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by TheJaredWilcurt** [djmisterjon/nw-Parcel-hmr-boilerplate#1]
could you make a simpler "hello world" version of this, with everything removed except for the bare minimum to get NW.js + Parcel to work together. There's just a lot of extra cruft (Pixi, React, RES, etc) that makes it difficult to see what is actually needed.

either as it's own repo or branch. I'd be happy to host/maintain it on nw-utils (repo of NW.js resources/boilerplates)

**Comment by djmisterjon** [comment]
@TheJaredWilcurt  ho , i had not seen your message, I will see when I have a little time this month.
it was actually a base for all my projects, but i will try make a super simple version.

**Comment by djmisterjon** [comment]
@TheJaredWilcurt 
finish , plz see branch `hellowWorld`
https://github.com/djmisterjon/nw-Parcel-hmr-boilerplate/tree/helloWorld

hope is ok and clear for you.
i up the `readme` and remove some node stuff dependency.
Now is fully supported inside inline scripts from package.json.
`npm i ` install nwjs and dependency for parcel and nwjs (parcel have dependence because have some limited CLI argument)
`npm run start-nw` - dev you app
`npm run build-nw` - final productions

Make a test and tell me if all fine or have questions, also dont hesitate to tell me if you have better approach ! am always curious.

**Comment by TheJaredWilcurt** [comment]
@djmisterjon I did some rewording and tweaks as a PR to try to simplify it for new people. But I think it's in really good shape!

**Comment by djmisterjon** [comment]
> @djmisterjon I did some rewording and tweaks as a PR to try to simplify it for new people. But I think it's in really good shape!
sure, nice, sorry and tanks for the english grammar !
